# DEPLOYMENT PATH TO CPANEL
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stormsco/StormsCompany
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp ./public/* /home/stormsco/public_html

deployment:
  tasks:
    - export DEPLOYPATH=/home/stormsco/Mtaa
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    #    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/* /home/stormsco/public_html/mtaa_public
