---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stormsco/StormsCompany
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp ./public/assets/* /home/stormsco/public_html/assets
    - /bin/cp ./public/build/* /home/stormsco/public_html/build
