# DEPLOYMENT PATH TO CPANEL
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stormsco/storms.co.ke
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    #    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    #- /bin/cp ./public/* /home/stormsco/public_html/storms_public

