# DEPLOYMENT PATH TO CPANEL
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stormsco/StormsCompany
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp -r ./public/assets/* /home/stormsco/public_html/assets
